- name: Commit and push changes
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add DeaTHlesS-Androiptv.m3u  # SADECE M3U DOSYASINI EKLE
    git commit -m "Auto-update M3U playlist - $(date)" || echo "No changes to commit"
    git pull origin main --rebase
    git push
